version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.15.1
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          key: vue-router-invoke-webpack-plugin-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: vue-router-invoke-webpack-plugin-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: npm run lint
      - run: npm run test:single
      - run: npm run test:ci
